INSERT INTO `web`.`imagens` (`id`, `alt`, `url`) VALUES ('1', 'Super Mario Bros Wonder Mídia Física', 'src/assets/img-mario-wonder.png');
INSERT INTO `web`.`imagens` (`id`, `alt`, `url`) VALUES ('2', 'The Legend Of Zelda Link\'s Awakening Mídia Física', 'src/assets/img-zelda-links-awakening.png');
INSERT INTO `web`.`imagens` (`id`, `alt`, `url`) VALUES ('3', 'Mario Party Superstars Mídia Física', 'src/assets/img-mario-party.png');
INSERT INTO `web`.`imagens` (`id`, `alt`, `url`) VALUES ('4', 'Donkey Kong Country Tropical Freeze Mídia Física', 'src/assets/img-donkey-kong.png');
INSERT INTO `web`.`imagens` (`id`, `alt`, `url`) VALUES ('5', 'The Legend Of Zelda Tears of Kingdom Mídia Física', 'src/assets/img-zelda-tears.png');
INSERT INTO `web`.`imagens` (`id`, `alt`, `url`) VALUES ('6', 'Mario Kart Deluxe Mídia Física', 'src/assets/img-mario-kart.png');

INSERT INTO `web`.`produtos` (`id`, `descricao`, `preco`, `titulo`, `id_imagem`) VALUES ('1', 'Super Mario Bros.™ Wonder: Encante-se com a evolução fenomenal da diversão com o Mario A jogabilidade clássica de deslocamento lateral dos jogos do Mario virou de cabeça para baixo com a chegada das flores fenomenais. Este item revolucionário ativa momentos tão espetaculares que é preciso ver para crer... Observe canos ganharem vida, use sua força devastadora como uma gigantesca bola com espinhos e até se surpreenda com situações inesperados - os eventos fenomenais. Escolha personagens heroicos de Super Mario™ e itens potenciadores Encare esta aventura como personagens conhecidos da série, como Mario, Luigi, Peach, Daisy, Yoshi e Toad. Até aí, nada de novo, mas… dessa vez você pode usar um item potenciador surpreendente para se transformar em um elefante! Use sua tromba para golpear inimigos! ', '349.00', 'Super Mario Bros Wonder Mídia Física', '1');
INSERT INTO `web`.`produtos` (`id`, `descricao`, `preco`, `titulo`, `id_imagem`) VALUES ('2', ' Você precisa saber da verdade! Link acorda em uma estranha terra longe de Hyrule, onde animais falam e monstros vagueiam. Para revelar a verdade por trás de seu paradeiro e despertar o legendário Wind Fish, explore Koholint Island e suas masmorras repletas de armadilhas, tudo isso reinventado com detalhes fascinantes para o novo lançamento de um dos mais amados jogos de The Legend of Zelda. Em sua jornada, você encontrará uma variedade divertidíssima de personagens encantadores, dos quais você nunca vai querer se despedir.', '349.00', 'The Legend Of Zelda Link\'s Awakening Mídia Física', '2');
INSERT INTO `web`.`produtos` (`id`, `descricao`, `preco`, `titulo`, `id_imagem`) VALUES ('3', 'Atenção, superestrelas! Mario Party está de volta com cinco tabuleiros clássicos dos jogos da série para Nintendo 64. Jogue para conseguir o máximo de estrelas (e sabotar seus adversários) em tabuleiros com o intergaláctico Espaçolândia ou o aterrorizante Medolâdia!', '349.00', 'Mario Party Superstars Mídia Física', '3');
INSERT INTO `web`.`produtos` (`id`, `descricao`, `preco`, `titulo`, `id_imagem`) VALUES ('4', 'Os invasores do Ártico transformaram a ilha de Donkey Kong em sua fortaleza pessoal congelada, e cabe a você salvar o dia.', '299.00', 'Donkey Kong Country Tropical Freeze Mídia Física', '4');
INSERT INTO `web`.`produtos` (`id`, `descricao`, `preco`, `titulo`, `id_imagem`) VALUES ('5', 'Uma aventura épica pela terra e pelos céus de Hyrule aguarda em The Legend of Zelda™: Tears of the Kingdom para o console Nintendo Switch™. A aventura será criada por você, em um mundo alimentado pela sua imaginação. Nesta continuação de The Legend of Zelda: Breath of the Wild, você decidirá seu próprio caminho pelas extensas paisagens de Hyrule e pelas misteriosas ilhas flutuantes. Você será capaz de aproveitar o poder das novas habilidades de Link para lutar contra as forças malévolas que ameaçam o reino? ', '329.90', 'The Legend Of Zelda Tears of Kingdom Mídia Física', '5');
INSERT INTO `web`.`produtos` (`id`, `descricao`, `preco`, `titulo`, `id_imagem`) VALUES ('6', 'Com este jogo Mario, você desfrutará de horas de diversão e novos desafios que lhe permitirão melhorar como jogador.', '279.90', 'Mario Kart Deluxe Mídia Física', '6');
